---
title: "Bayesian statistical modeling by Stan&R introduction (the book by baba)"
subtitle: "08"
author: "tmyst"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
  highlight: zenburn
  md_extensions: -ascii_identifiers
  self_containd: true
  lightbox: true
  toc_float: true
  toc_depth: 3
---
  
data was downloaded from [this website](https://github.com/logics-of-blue/book-r-stan-bayesian-model-intro)
```{r knitr_init, cache=FALSE, include=FALSE}
rm(list = ls(all.names = T))
library(knitr)
library(rmdformats)
library(ggsci)
library(ggfortify)
library(scico)
library(RColorBrewer)
library(wesanderson)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r}
library(tidyverse)
library(rstan)
library(brms)
rstan_options(auto_write = T)
options(mc.cores = parallel::detectCores())

```

```{r}
df <- read_csv("/Users/tomoya/Documents/dataset/bayesian_intro_baba/3-8-1-fish-num-1.csv")
df
```
```{r}
contents <- mosaic::inspect(df)
contents[[1]]
```

```{r}
contents[[2]]
```

```{r}
library(viridis)
library(hrbrthemes)
df %>% ggplot() + geom_histogram(aes(x=fish_num)) + theme_ipsum() + 
  theme(axis.title.x = element_text(size = 11), 
        axis.title.y = element_text(size = 11))
```

```{r}
library(ggsci)
library()
df %>% ggplot() + geom_point(aes(x = temperature, y = fish_num, color = weather, shape = weather), size = 2.5) +
  scale_color_manual(values = c("#69b3a2", "#404080")) + theme_ipsum(base_size = 12) + 
  theme(axis.title.x = element_text(size = 12), 
        axis.title.y = element_text(size = 12), 
        legend.text = element_text(size = 12), 
        legend.title = element_text(size = 13)) 
```

```{r}
glm_pois_brms <- brm(
  formula = fish_num ~ weather + temperature,
  family = poisson(),
  data = df,
  seed = 1,
  prior = c(set_prior("", class = "Intercept"))
)
```

```{r}
glm_pois_brms
```
```{r}
as.mcmc(glm_pois_brms, combine_chains = T) %>% bayesplot::mcmc_intervals(pars = c("b_Intercept"), prob = 0.8, prob_outer = 0.95) + theme_bw(base_size = 14) 
```
```{r}
eff <- marginal_effects(glm_pois_brms, effects = "temperature:weather")
plot(eff, points = T)[[1]] + 
  theme_ipsum(base_size = 13) + 
  scale_color_aaas() +
  scale_fill_aaas() + 
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13), 
        legend.title = element_text(size = 13), 
        legend.text = element_text(size = 12), 
        legend.position = c(0.04, 0.96), legend.justification = c(0, 1),
        legend.background = element_rect(color = "gray70"))
```

```{r}
mcmc_glm_pois <- as.mcmc(glm_pois_brms, combine_chains = T)
mcmc_temperature <- mcmc_glm_pois[, "b_temperature"]
mcmc_weathersunny <- mcmc_glm_pois[, "b_weathersunny"]
mcmc_Intercept   <- mcmc_glm_pois[, "b_Intercept"]
n_coeffs <- length(dimnames(mcmc_glm_pois)[[2]])-1
plotlist_mcmc_area <- lapply(1:n_coeffs, function(i){
  mcmc_glm_pois %>% bayesplot::mcmc_areas( pars = dimnames(mcmc_glm_pois)[[2]][i]) + theme_bw(base_size = 14)
})
plotlist_mcmc_area
```

Reploduce marginal-effect graph directly using mcmc samples
```{r}
fm  <- formula(fish_num ~ weather + temperature)
mat <- model.matrix(fm, df)

## factors and numerics in original data
weathersunny_unique <- mat[, "weathersunny"] %>% unique # used in strata
temperature_unique  <- mat[, "temperature"] %>% unique %>% unique # x axis variable

## reproduce predected values using real explanatory variables
dup_mcmc    <- function(mcmc, n) { apply(matrix(mcmc, nrow = 1), MARGIN = 2, FUN = function(x)rep(x, n)) }

## predict values using simulated variables
pred_lambdas <- lapply(weathersunny_unique, function(x){
  dup_mcmc(mcmc_Intercept, length(temperature_unique)) + 
    temperature_unique  %*% t(mcmc_temperature) + 
    rep(x, length(temperature_unique)) %*% t(mcmc_weathersunny)
})

qts_pred_lambda  <- lapply(pred_lambdas, function(X){
  mx <- apply(X, MARGIN = 1, FUN = function(x) c( mean(x), quantile(x, probs = c(0.025, 0.1, 0.5, 0.9, 0.975)))) %>% t
  colnames(mx) <- c("mean", "p2.5", "p10", "p50", "p90", "p97.5")
  mx
  }) %>% setNames(nm = c("cloudy", "sunny"))

df_qts_pred_lambda <- lapply(names(qts_pred_lambda), function(name){ 
  qts_pred_lambda[[name]] %>% 
    data.frame(check.names = F) %>%  
    add_column(weather = name, .before = T) 
  }) %>% 
  bind_rows()

data.frame(temperature = temperature_unique, df_qts_pred_lambda, check.names = F) %>% 
  ggplot() + 
  geom_line(aes(x = temperature, y = exp(mean), color = weather)) +
  geom_ribbon(aes(x = temperature, ymin = exp(p2.5), ymax = exp(p97.5), fill = weather), alpha = 0.4) +
  theme_bw(base_size = 14, base_rect_size = 0, base_line_size = 1) +  
  scale_fill_nejm() + 
  scale_color_nejm() +
  geom_point(data = df, mapping = aes(x = temperature, y = fish_num, color = weather, shape = weather), size = 2) +
  ylab("fish_num")

```

```{r}
list(
  (df$temperature %*% t(mcmc_temperature))[1, ] %>% data.frame(x = .) %>% 
  ggplot() + geom_density(aes(x=x), fill = "skyblue3", color = "gray", alpha = 0.5) + theme_bw(), 
  (df$temperature %*% t(mcmc_temperature))[1, ] %>% data.frame(x = .) %>% 
  ggplot() + geom_density(aes(x=x), fill = "skyblue3", color = "gray", alpha = 0.5) + theme_bw() 
)
```
```{r}
eff_pre <- marginal_effects(glm_pois_brms, method = "predict", effects = "temperature:weather", probs = c(0.005, 0.995))
plot(eff_pre, points = T)[[1]] +  
  theme_ipsum(base_size = 13) + 
  scale_color_lancet() +
  scale_fill_lancet() + 
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13), 
        legend.title = element_text(size = 13), 
        legend.text = element_text(size = 12), 
        legend.position = c(0.04, 0.96), legend.justification = c(0, 1),
        legend.background = element_rect(color = "gray70"))
```

```{r}
pred_mat <- expand.grid(weather = df$weather %>% unique, temperature = seq(0, 30, 0.5)) %>% 
  mutate(weathersunny = ifelse(weather == "sunny", 1, 0)) 

pred_bx    <- dup_mcmc(mcmc_Intercept, nrow(pred_mat)) + 
  pred_mat$temperature %*% t(mcmc_temperature) + 
  pred_mat$weathersunny %*% t(mcmc_weathersunny)

pred_lambda <- exp(pred_bx)

set.seed(10)
generate_pois_pred <- function(lambdas, n_repeat){
  res <- lapply(1:nrow(lambdas), function(i){
    lambda_row <- lambdas[i, ]
    sapply(lambda_row, function(x){rpois(n=n_repeat, lambda = x)}) %>% as.vector()
  })
  res
}
generated_values <- generate_pois_pred(pred_lambda, 10)

qts_gen_values  <- lapply(generated_values, function(X){
  qts <- c(mean(X), quantile(X, probs = c(0.005, 0.1, 0.5, 0.9, 0.995)))
  names(qts) <- c("mean", "p0.5", "p10", "p50", "p90", "p99.5")
  qts
  }) %>% do.call(rbind, .) %>% data.frame(check.names = F)

df_qts_gen_values <- bind_cols(pred_mat, qts_gen_values)

manual_colors <- c("#69B3A2", "#404080")
df_qts_gen_values %>% ggplot() + 
  geom_line(mapping = aes(x = temperature, y = p50, color = weather), size = 1) + 
  geom_point(data = df, mapping = aes(x = temperature, y = fish_num, color = weather, shape = weather), size = 2) + 
  geom_ribbon(mapping = aes( x = temperature, ymin =p0.5, ymax = p99.5, fill = weather), alpha=0.3) + 
  theme_bw(base_size = 14, base_rect_size = 0, base_line_size = 1) +
  scale_color_aaas() +
  scale_fill_aaas() +
  ylab("number of fish") +
  ylim(c(0, 13)) +
  theme(legend.position = c(0.045, 0.99), 
        legend.justification = c(0, 1), 
        legend.background = element_rect(size = 1, color = "gray80"))

```

```{r}
poisson_formula <- formula(fish_num ~ temperature + weather)
data_mat <- model.matrix(poisson_formula, data = df)

stan_pois <- stan(
  file = "fish_poisson.stan",
  data = list(
    N = nrow(df), 
    y = df$fish_num, 
    weathersunny = data_mat[,3], 
    temperature = df$temperature),
  chains = 4,
  iter = 2000, 
  thin = 1, 
  warmup = 1000
)
```

```{r}
stan_result <- rstan::extract(stan_pois, permuted = F)
param_names <- dimnames(stan_result)$parameters

list_qts_stan <- lapply(param_names[1:length(param_names)-1], 
  function(name){
    c(mean(stan_result[,,name]), quantile(stan_result[,,name], probs = c(0.025, 0.1, 0.5, 0.9, 0.975))) %>% 
      setNames(nm = c("mean", "p2.5", "p10", "p50", "p90", "97.5"))
    }) %>% 
  do.call(bind_rows, .) %>% 
  add_column(params = param_names[1:length(param_names)-1], .before = T)

list_qts_stan
```
```{r}
stan_Intercept      <- stan_result[,,param_names[1]] %>% as.vector() 
stan_b_temperature  <- stan_result[,,param_names[2]] %>% as.vector()
stan_b_weathersunny <- stan_result[,,param_names[3]] %>% as.vector()
stan_pred_bx    <- dup_mcmc(stan_Intercept, nrow(pred_mat)) + 
  pred_mat$temperature %*% t(stan_b_temperature) + 
  pred_mat$weathersunny %*% t(stan_b_weathersunny)

stan_pred_lambda <- exp(stan_pred_bx)

set.seed(10)
stan_generated_values <- generate_pois_pred(stan_pred_lambda, 10)

stan_qts_gen_values  <- lapply(stan_generated_values, function(X){
  qts <- c(mean(X), quantile(X, probs = c(0.005, 0.1, 0.5, 0.9, 0.995)))
  names(qts) <- c("mean", "p0.5", "p10", "p50", "p90", "p99.5")
  qts
  }) %>% do.call(rbind, .) %>% data.frame(check.names = F)

df_stan_qts_gen_values <- bind_cols(pred_mat, stan_qts_gen_values)

manual_colors <- c("#69B3A2", "#404080")
df_stan_qts_gen_values %>% ggplot() + 
  geom_line(mapping = aes(x = temperature, y = p50, color = weather), size = 1) + 
  geom_point(data = df, mapping = aes(x = temperature, y = fish_num, color = weather, shape = weather), size = 2) + 
  geom_ribbon(mapping = aes( x = temperature, ymin =p0.5, ymax = p99.5, fill = weather), alpha=0.3) + 
  theme_bw(base_size = 14, base_rect_size = 0, base_line_size = 1) +
  scale_color_manual(values = manual_colors) +
  scale_fill_manual(values = manual_colors) +
  ylab("number of fish") +
  ylim(c(0, 13)) +
  theme(legend.position = c(0.045, 0.99), 
        legend.justification = c(0, 1), 
        legend.background = element_rect(size = 1, color = "gray80"))
```

