---
title: "BAMLSS_01"
author: "Tmyst"
date: "2020/3/2"
output:
  rmdformats::readthedown:
    highlight: zenburn
    md_extension: -ascii_identifiers
    self_contained: true
    lightobx: true
    toc_float: true
    toc_depth: 3
---

```{r set_options, echo=F, cache=F}

```

```{r}
library(knitr)
library(tidyverse)
library(data.table)
library(bamlss)
library(ggsci)
theme_set(theme_bw() + theme(axis.text.x = element_text(size = 12), 
                             axis.text.y = element_text(size = 12), 
                             axis.title.x = element_text(size = 14), 
                             axis.title.y = element_text(size = 14)))
```

```{r}
data("SwissLabor", package = "AER")
```

```{r}
df <- SwissLabor
df %>% skimr::skim()
```
#### univariate
```{r}
yvar <- names(df)[1]
xvars <- names(df)[-1]
fvars <- xvars[6]
nvars <- xvars[-6]
{
  fvars %>% print
  nvars %>% print
}
```

```{r, fig.width=10, fig.height=6}
gs <- map(nvars, ~ ggplot() + geom_histogram(aes_string(x = .x), bins=16, data = df, fill ="skyblue4"))
do.call(gridExtra::grid.arrange, gs)
```

```{r, fig.width=3, fig.height=2}
gs <- map(fvars, ~ggplot() + geom_bar(aes_string(x = .x), data= df, fill = "skyblue4"))
do.call(gridExtra::grid.arrange, gs)
```

```{r, fig.width=10, fig.height=6}
gs <- map(nvars, ~ ggplot(df) + geom_count(aes_string(x = .x, y = yvar), alpha = 0.2, color = "skyblue4"))
do.call(gridExtra::grid.arrange, c(gs, ncol = 2))
```

```{r, fig.width=10, fig.height=6}
gs <- map(nvars, ~ ggplot(df) + geom_boxplot(aes_string(x = .x, y = yvar), fill = "skyblue3", alpha=0.5, color= "skyblue4"))
do.call(gridExtra::grid.arrange, c(gs, ncol = 2))
```

```{r, fig.width=10, fig.height=6}
out_len <- 3
gs <- map(nvars, function(x){
  lens <- c(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
  intervals <- 1/lens
  if(out_len %>% is.na){
    out_len  <- df[[x]] %>% unique %>% length
    interval <- intervals[which.min(abs(lens - (out_len)))]
  }else if(out_len > df[[x]] %>% unique %>% length) {
    out_len <-  df[[x]] %>% unique %>% length
    interval <- intervals[which.min(abs(lens - (out_len)))]
  }else{
    interval <- 1/(out_len)
  }
  qs <- df[[x]] %>% quantile(probs = seq(0, 1, interval)) %>% unique
  if(length(qs) <= out_len) {
    qs <- unique(df[[x]]) %>% sort 
    out_len <- length(qs)
    temp_df <- df %>% group_by(!!sym(yvar), !!sym(x))  
  }else{
    temp_df <- df %>% mutate(!!sym(x) := cut(!!sym(x), breaks = qs, include.lowest = T, right = T)) %>% 
    group_by(!!sym(yvar), !!sym(x))
  }
  temp_df <- temp_df %>% 
    dplyr::summarize(count = dplyr::n()) %>% 
    group_by(!!sym(x)) %>% mutate(sum_count = sum(count), ratio = count/sum_count) %>% 
    ungroup()

  ggplot(temp_df) + geom_col(aes(x = !!sym(x), y = ratio, fill = !!sym(yvar)))+
    geom_label(aes(x = !!sym(x), y = ifelse(participation=="no", 0.75, 0.25), label = count)) + 
    scale_fill_npg()
  
})
do.call(gridExtra::grid.arrange, c(gs, ncol = 2))
```

```{r, fig.width = 10, fig.height=6}
combs <- combn(nvars[-4:-5], m = 2)
out_len <- 4
gs <- lapply(1:ncol(combs), function(i){
  comb <- combs[,i]
  temp_df <- df %>% 
    mutate(!!sym(comb[1]) := cut_number(!!sym(comb[1]), out_len)) %>% 
    mutate(!!sym(comb[2]) := cut_number(!!sym(comb[2]), out_len)) %>% 
    group_by(!!sym(comb[1]), !!sym(comb[2])) %>% 
    mutate(count_yes = sum(ifelse(!!sym(yvar)=="yes", 1, 0))) %>% 
    mutate(yes_ratio = count_yes/dplyr::n()) %>% 
    select(comb[1], comb[2], count_yes, yes_ratio) %>% 
    distinct %>% 
    arrange(!!sym(comb[1]), !!sym(comb[2]))
  
  xs <- temp_df[[comb[1]]] %>% unique %>% sort
  ys <- temp_df[[comb[2]]] %>% unique %>% sort
  f  <- Vectorize(function(x,y) (temp_df %>% filter(!!sym(comb[1])==x, !!sym(comb[2])==y))$yes_ratio)
  zs <- outer(xs, ys, f)
  
  g1 <- ggplot(aes(x = as.integer(!!sym(comb[1])), y=as.integer(!!sym(comb[2])), z = yes_ratio, color = stat(level)), data = temp_df) +
    geom_contour() +
    xlab(comb[1]) + ylab(comb[2]) +
    scale_x_continuous(breaks = xs %>% as.integer, labels = xs) +
    scale_y_continuous(breaks = xs %>% as.integer, labels = ys) + 
    theme(axis.text.x = element_text(size = 11, angle = 0))+
    scale_colour_distiller(palette = "BuGn", direction = 1)+
    theme_grey()
  
  g2 <- ggplot(aes(x = as.integer(!!sym(comb[1])), y=as.integer(!!sym(comb[2])), z = yes_ratio), data = temp_df) +
    stat_contour(geom = "polygon", aes(fill = stat(level))) +
    xlab(comb[1]) + ylab(comb[2]) +
    scale_x_continuous(breaks = xs %>% as.integer, labels = xs) +
    scale_y_continuous(breaks = xs %>% as.integer, labels = ys) + 
    theme(axis.text.x = element_text(size = 11, angle = 0))+
    scale_fill_distiller(palette = "Spectral", direction = 1) + 
    theme_grey()
  g2
})
do.call(gridExtra::grid.arrange, c(gs, ncol = 2))
```

#### The response to age seems to be distributed along age^2
```{r}
f <- participation ~ income + age + education + youngkids + oldkids + foreign + I(age^2)
b <- bamlss(f, family = "binomial", data = SwissLabor)
```

```{r}
summary(b)
```

```{r}
plot(b, which = c("samples", "max-acf"))
```

```{r}
nd <- data.frame(income = 11, age = seq(2, 6.2, length = 100), education = 12, youngkids = 1, oldkids = 1, foreign = "no")
nd$pSwiss <- predict(b, newdata = nd, type = "parameter", FUN = c95)
nd$foreign <- "yes"
nd$pForeign <- predict(b, newdata = nd, type = "parameter", FUN = c95)

```

```{r}
blues <- function(n, ...) sequential_hcl(n, "Blues", rev = T)
{
  plot2d(pSwiss ~ age, data = nd, ylab = "participation", ylim = range(c(nd$pSwiss, nd$pForeign)), fill.select = c(0,1,0,1))
  plot2d(pForeign ~ age, data = nd, add = T, fill.select = c(0,1,0,1), axes = F, s2.col = blues, col.lines = blues(1))
}


```

```{r}
f2 <- participation ~ income + education + youngkids + oldkids + foreign + s(age, k = 10)
set.seed(123)
b2 <- bamlss(f, family = "binomial", data = SwissLabor)
```
```{r}
summary(b2)
```

```{r}
plot(b2, which = c("samples", "max-acf"))
```
```{r}
plot(b2, term = "s(age)")
```

```{r}
nd2 <- nd
nd2$foreign <- "no"
nd2$pSwiss <- predict(object = b2, newdata = nd2, type = "parameter", FUN = c95)
nd2$foreign <- "yes"
nd2$pForeign <- predict(object = b2, newdata = nd2, type = "parameter", FUN = c95)
{
  plot2d(pSwiss ~ age, data = nd2, ylab = "participation", ylim = range(c(nd$pSwiss, nd$pForeign)), fill.select = c(0,1,0,1))
  plot2d(pForeign ~ age, data = nd2, add = T, fill.select = c(0,1,0,1), axes = F, s2.col = blues, col.lines = blues(1))
}

```
#### Varialbe selection
```{r}
df <- SwissLabor
df <- df %>% mutate(cage = cut(age, breaks = quantile(age, probs = seq(0, 1, length.out = 11)), i = T, ordered_result = T))

```

```{r}
f3 <- participation ~ income + education + youngkids + oldkids + foreign + la(cage, fuse = 2)
b3 <- bamlss(f3, family = "binomial", data = df, optimizer = lasso, sampler = F, criterion = "BIC", upper = exp(5), lower = 1)
```
```{r}
summary(b3)
```
```{r, fig.height=5}
pathplot(b3)

```
```{r}
df$page <- predict(b3, term = "cage", intercept = F, mstop = lasso_stop(b3))
plot2d(page ~ age, data = df, rug = T)
```

```{r}
data("mcycle", package = "MASS")
mcycle %>% skimr::skim()
```

```{r}
mcycle
```

```{r}
qplot(x = times, y = accel, data = mcycle)
f4 <- accel ~ s(times)
b4 <- bamlss(f4, family = "gaussian", data = mcycle)
```
```{r}
summary(b4)
```

```{r}
plot(b4)
```

```{r}
f5 <- list(accel ~ s(times, k = 20), sigma ~ s(times, k = 20))
set.seed(456)
b5 <- bamlss(f5, family = "gaussian", data = mcycle)
```
```{r}
plot(b5, model = c("mu", "sigma"))
```
```{r}
residuals(b5) %>% plot
```
```{r}
plot(b5, which = c("hist-resid", "qq-resid"))
```
```{r}
DIC(b4)
```
#### design
```{r}
df <- SwissLabor
f <- participation ~ income + age + education + youngkids + oldkids + age + I(age^2)
bf <- bamlss.frame(f, data = df, family = "binomial")
summary(bf)
```
#### backfitting estimation to decide starting values for the MCMC sampler
```{r}
pm <- with(bf, bfit(x, y, family))
```

```{r}
set.seed(124)
samps <- with(bf, GMCMC(x, y, family, start = pm$parameters))
```

```{r}
stats <- with(bf, samplestats(samps, x, y, family))
stats
```

