---
title: "GAMLSS_01"
author: "Tmyst"
date: "2020/3/2"
output:
  rmdformats::readthedown:
    highlight: zenburn
    md_extension: -ascii_identifiers
    self_contained: true
    lightobx: true
    toc_float: true
    toc_depth: 3
---

```{r knitr_init, cache=FALSE, include=FALSE}

rm(list = ls(all.names = T))
gc();gc()
library(tidyverse)
library(knitr)
library(rmdformats)
library(ggsci)
library(hrbrthemes)

options(max.print="100")
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)

```

# rent data set
```{r}
#install.packages("gamlss")
library(gamlss)
```


```{r}
df <- rent
df %>% skimr::skim()
```


```{r}
set.seed(1290)

df <- df %>% 
  add_column(set = sample(x = 1:nrow(df), replace = F, size = nrow(df))) %>% 
  mutate(set = ifelse(set<=nrow(df)/4, "test", "train"))

x_train <- df %>% filter(set == "train") %>% dplyr::select(-R)
y_train <- df %>% filter(set == "train") %>% dplyr::select(R)

x_test <- df %>% filter(set == "test") %>% dplyr::select(-R)
y_test <- df %>% filter(set == "test") %>% dplyr::select(R)

```

# [useful example for qplot](http://www.sthda.com/english/wiki/qplot-quick-plot-with-ggplot2-r-software-and-data-visualization)
```{r}
theme_set(theme_bw())
y_fl  <- qplot(x = Fl, y = R, data = rent, geom="auto")
y_a   <- qplot(x = A, y = R, data = rent, geom="auto")

y_sp <- qplot(x = factor(Sp), y = R, data = rent, geom = "boxplot")
y_sm <- qplot(x = factor(Sm), y = R, data = rent, geom = "boxplot")
y_b   <- qplot(x = B, y = R, data = rent, geom="boxplot");y_b
y_h   <- qplot(x = H, y = R, data = rent, geom="boxplot")
y_loc <- qplot(x = loc, y = R, data = rent, geom="boxplot")
y_l <- qplot(x = L, y = R, data = rent, geom = "boxplot")

g_num <- gridExtra::arrangeGrob(y_fl, y_a, nrow = 2)
g_cat <- gridExtra::arrangeGrob(y_b, y_h, y_l, y_loc, y_sp, y_sm, ncol = 2)
plot(g_num)
```

```{r}
plot(g_cat)
```


```{r}
gmls_01 <- gamlss(R ~ Fl+A+H+loc+B+L, family = NO, data = rent, trace = F)
lm_01 <- lm(R ~ Fl+A+H+loc+B+L, data = rent)
gmls_01 %>% coef
```

```{r}
lm_01 %>% coef
```

```{r}
fitted(gmls_01, "sigma")[1]
```


```{r}
summary(gmls_01)
```


```{r}
gmls_02 <-  gamlss(R ~ Fl+A+H+loc+B+L, family=GA,  data=rent)
gmls_02 %>% summary
```


```{r}
coef(gmls_02)
```

```{r}
coef(gmls_02, "sigma")
```

$$\rm{Dev}_{\small\rm{GAMLSS}} = -2\mathrm{log}{\it\hat{L}}_{current-model}$$
```{r}
deviance(gmls_02)
```

ˆ
```{r}
lm_02 <- glm(R~Fl+A+H+loc+B+L, family=Gamma(link = "log"), data = rent)
summary(lm_02)
```

```{r}
lm_02 %>% summary %>% attributes
list(
  summary(lm_02)$call
  ,summary(lm_02)$terms
  ,summary(lm_02)$family
  ,summary(lm_02)$deviance
  ,summary(lm_02)$aic
  ,summary(lm_02)$contrasts
  ,summary(lm_02)$df.residual
  ,summary(lm_02)$null.deviance
  ,summary(lm_02)$df.null
  ,summary(lm_02)$iter
  ,summary(lm_02)$deviance.resid
  ,summary(lm_02)$coefficients
  ,summary(lm_02)$aliased
  ,summary(lm_02)$dispersion
  ,summary(lm_02)$df
  ,summary(lm_02)$cov.unscaled
  ,summary(lm_02)$cov.scaled
)

```

$$\rm{Dev}_{\rm\small{GLM}} = -2log\left(\frac{{\it{L}}_{current-model}}{{\it{L}}_{saturated}}\right)$$
```{r}
deviance(lm_02)
```
$$\rm{GAIC}=-2\mathrm{log}{\it\hat{L}}_c + (\kappa \times df)$$
```{r}
gmls_03 <- gamlss(R ~ Fl+A+H+loc+B+L, family=IG, data=rent, trace=FALSE)
GAIC(gmls_01, gmls_02, gmls_03, k=0)
```

```{r}
plot(gmls_02)
```

```{r}
plot(gmls_03)
```

+ Applying spline
```{r}
gmls_04 <- gamlss(R ~ pb(Fl)+pb(A)+H+loc+L+B, data =df, family = GA, trace = F)
AIC(gmls_02, gmls_04)
```

```{r}
summary(gmls_04)
```

+ cgam: An R Package for the Constrained Generalized Additive Model
```{r}
surf <- data.frame(x1 = seq(0, 1, 0.01), x2 = seq(0, 1, 0.01)) %>% mutate(fxx = 4*(x1 + x2 -x1*x2))
x1_y <- qplot(x = x1, y = fxx, data = surf)
x2_y <- qplot(x = x2, y = fxx, data = surf)
gridExtra::grid.arrange(x1_y, x2_y)
```

```{r}
# install.packages("cgam")
library(cgam)
data("Rubber", package = "MASS")
Rubber %>% skimr::skim()
```

```{r}
g <- gridExtra::arrangeGrob(
  qplot(y = loss, x = hard, data = Rubber), 
  qplot(y = loss, x = tens, data = Rubber)
)
plot(g)
```

```{r}
#install.packages("ggstatsplot")
library(ggstatsplot)
ggcorrmat(Rubber, sig.level = 0.1)
```
```{r}
fit_decr <- cgam(loss ~ decr(hard) + decr(tens), family = gaussian, data= Rubber)
fit_decr %>% summary
```
```{r}
fit_s_decr <- cgam(loss~ s.decr(hard) + s.decr(tens), family = gaussian, data = Rubber)
fit_s_decr %>% summary
```
```{r}
fit_s <- cgam(loss ~ s(hard) + s(tens), family = gaussian, data = Rubber)
fit_s %>% summary
```

```{r}
g <- gridExtra::arrangeGrob(
  qplot(x = fitted(fit_decr),   y = Rubber$loss) + xlab("fitted") + ylab("y") + ggtitle("decr"),
  qplot(x = fitted(fit_s_decr), y = Rubber$loss) + xlab("fitted") + ylab("y") + ggtitle("s, decr"),
  qplot(x = fitted(fit_s),      y = Rubber$loss) + xlab("fitted") + ylab("y") + ggtitle("s"),
  grid::grid.rect(gp=grid::gpar(col="white")),
  ncol = 2
)
plot(g)
```
```{r}
list(fit_s$cic, fit_decr$cic, fit_s_decr$cic)
```

```{r}
par(mfrow = c(1, 3))
list(
  plotpersp(fit_decr, hard, tens, data = Rubber, th = 120, main = "(a)", ngrid = 31),
  plotpersp(fit_s_decr, hard, tens, data = Rubber, th = 120, main = "(b)", ngrid = 31),
  plotpersp(fit_s, hard, tens, data = Rubber, th = 120, main = "(c)", ngrid = 31)
)
```
```{r}
data("plasma", package = "cgam")
inspect <- plasma %>% mosaic::inspect()
inspect
```
```{r}
plasma %>% map(~unique(.) %>% length) %>% unlist
```
+ for categorical variables
```{r}
qp_list <- lapply(c("smoke", "vituse"), function(x){
  qplot(x = factor(!!sym(x)), y = logplasma, data = plasma, geom = "boxplot")
})
do.call(gridExtra::grid.arrange, c(qp_list, list(ncol = 2)))
```
+ for numerical variables
```{r}
qp_list <- lapply(names(plasma)[2:7], function(x){
  qplot(x = !!sym(x), y = logplasma, data = plasma, geom = "auto")
  })
g <- do.call(gridExtra::arrangeGrob, c(qp_list, list(ncol = 2)))
plot(g)
```

```{r}
fit <- cgam(logplasma ~ s.decr(bmi) + 
              s.decr(logdietfat) + s.decr(cholest) + 
              s.incr(fiber) + s.incr(betacaro) + 
              s.incr(retinol) + factor(smoke) + factor(vituse), 
            data = plasma)
summary(fit)
```

```{r}
par(mfrow = c(1,2))

plotpersp(fit, bmi, fiber, categ = "factor(smoke)", 
          data = plasma, main = "by smoke", ngrid = 41, th = 120, 
          nticks = 5, ticktype = "detailed", cex.axis = .6)

plotpersp(fit, bmi, fiber, categ = "factor(vituse)", 
          data = plasma, main = "by vituse", ngrid = 41, th = 120,
          nticks = 5, ticktype = "detailed", cex.axis = .6)
```

```{r}

```

```{r}

```

